apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: space-inv-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: space-inv
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60