apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: space-inv
  name: space-inv
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: space-inv
  type: LoadBalancer
status:
  loadBalancer: {}
